import * as fs from 'fs-extra';
import * as path from 'path';

export const POST_COMMIT_SCRIPT = `#!/bin/sh
# HackBridge Post-Commit Hook
# Auto-generated by hackbridge-cli

# Exit 0 always — never block a commit
trap "exit 0" EXIT

STATE_FILE=".hackbridge/state.json"
if [ ! -f "$STATE_FILE" ]; then
  exit 0
fi

TEAM_CODE=$(node -e "console.log(require('./.hackbridge/state.json').team_code)")
EVENT_CODE=$(node -e "console.log(require('./.hackbridge/state.json').event_code)")
CLI_TOKEN=$(node -e "console.log(require('./.hackbridge/state.json').cli_token || '')")
API_BASE=$(node -e "console.log(require('./.hackbridge/state.json').api_base)")

if [ -z "$TEAM_CODE" ] || [ -z "$API_BASE" ]; then
  exit 0
fi

COMMIT_MSG=$(git log -1 --format="%s")
FILES_CHANGED=$(git diff-tree --no-commit-id -r --name-only HEAD)
PATCH=$(git diff-tree --no-commit-id -r --patch HEAD)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Send to HackBridge via Node for safe escaping
node -e "
const http = require('http');
const https = require('https');
const data = JSON.stringify({
  team_code: process.argv[1],
  event_code: process.argv[2],
  cli_token: process.argv[3],
  message: process.argv[4],
  files_changed: process.argv[5].split('\\n').filter(Boolean),
  patch: process.argv[6],
  timestamp: process.argv[7]
});

const url = process.argv[8] + '/commits/';
const client = url.startsWith('https') ? https : http;

const req = client.request(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(data)
  }
}, (res) => {});

req.on('error', (e) => {});
req.write(data);
req.end();
" "$TEAM_CODE" "$EVENT_CODE" "$CLI_TOKEN" "$COMMIT_MSG" "$FILES_CHANGED" "$PATCH" "$TIMESTAMP" "$API_BASE" &

exit 0
`;

export async function installGitHook(cwd: string) {
  const hookPath = path.join(cwd, '.git', 'hooks', 'post-commit');
  
  if (!await fs.pathExists(path.join(cwd, '.git'))) {
    throw new Error('Not a git repository. Please run `git init` first.');
  }

  await fs.writeFile(hookPath, POST_COMMIT_SCRIPT);
  await fs.chmod(hookPath, 0o755); // Make executable
}
