import * as fs from 'fs-extra';
import * as path from 'path';

export const POST_COMMIT_SCRIPT = `#!/bin/sh
# HackBridge Post-Commit Hook
# Auto-generated by hackbridge-cli

# Exit 0 always — never block a commit
trap "exit 0" EXIT

STATE_FILE=".hackbridge/state.json"
if [ ! -f "$STATE_FILE" ]; then
  exit 0
fi

TEAM_CODE=$(grep -o '"team_code": *"[^"]*"' $STATE_FILE | grep -o '"[^"]*"$' | tr -d '"')
EVENT_ID=$(grep -o '"event_id": *"[^"]*"' $STATE_FILE | grep -o '"[^"]*"$' | tr -d '"')
API_BASE=$(grep -o '"api_base": *"[^"]*"' $STATE_FILE | grep -o '"[^"]*"$' | tr -d '"')

if [ -z "$TEAM_CODE" ] || [ -z "$API_BASE" ]; then
  exit 0
fi

COMMIT_HASH=$(git log -1 --format="%H")
COMMIT_MSG=$(git log -1 --format="%s")
FILES_CHANGED=$(git diff-tree --no-commit-id -r --name-only HEAD | tr '\\n' ',')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Fire and forget POST request
curl -X POST "$API_BASE/commits/" \\
  -H "Content-Type: application/json" \\
  -d '{
    "team_code": "'"$TEAM_CODE"'",
    "event_code": "'"$EVENT_ID"'",
    "message": "'"$COMMIT_MSG"'",
    "files_changed": ["'"$FILES_CHANGED"'"],
    "timestamp": "'"$TIMESTAMP"'"
  }' > /dev/null 2>&1 &

exit 0
`;

export async function installGitHook(cwd: string) {
  const hookPath = path.join(cwd, '.git', 'hooks', 'post-commit');
  
  if (!await fs.pathExists(path.join(cwd, '.git'))) {
    throw new Error('Not a git repository. Please run `git init` first.');
  }

  await fs.writeFile(hookPath, POST_COMMIT_SCRIPT);
  await fs.chmod(hookPath, 0o755); // Make executable
}
